version: "3"
services:
  app:
    build: ./docker/dev/app
    container_name: dietwater_app
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/dietwater:cached
    links:
      - db
  webserver:
    image: nginx:latest
    container_name: dietwater_webserver
    ports:
      - "80:80"
    links:
      - app
    volumes:
      - ./app:/var/www/dietwater:cached
      - ./docker/dev/webserver/dietwater.conf:/etc/nginx/conf.d/default.conf
  db:
    image: mysql:5.7
    container_name: dietwater_db
    ports:
      - "3306:3306"
#    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dietwater
      MYSQL_USER: dietwater
      MYSQL_PASSWORD: dietwater
